{-# LANGUAGE GHC2024 #-}
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeFamilyDependencies #-}
-- Mode-indexed array superclass constraints contain type families.
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE UndecidableSuperClasses #-}

-- |
-- Module      :   Grisette.Internal.Unified.UnifiedArray
-- Copyright   :   (c) Sirui Lu 2024
-- License     :   BSD-3-Clause (see the LICENSE file)
--
-- Maintainer  :   siruilu@cs.washington.edu
-- Stability   :   Experimental
-- Portability :   GHC only
module Grisette.Internal.Unified.UnifiedArray
  ( GetArray,
    UnifiedArray (..),
    UnifiedArrayConstraint,
    UnifiedScalarArray,
    UnifiedBVArray,
    EvalModeArray (..),
  )
where

import Data.Hashable (Hashable)
import GHC.TypeNats (KnownNat, Nat, type (<=))
import Grisette.Internal.Core.Data.Class.Mergeable (Mergeable)
import Grisette.Internal.SymPrim.Array (Array)
import qualified Grisette.Internal.SymPrim.Array as CArr
import Grisette.Internal.SymPrim.Prim.Term
  ( ConRep (ConType),
    LinkedRep,
    SupportedNonFuncPrim,
  )
import Grisette.Internal.SymPrim.SymArray (SymArray)
import qualified Grisette.Internal.SymPrim.SymArray as SArr
import Grisette.Internal.Unified.Class.UnifiedITEOp (UnifiedITEOp)
import Grisette.Internal.Unified.Class.UnifiedSimpleMergeable
  ( UnifiedSimpleMergeable,
  )
import Grisette.Internal.Unified.Class.UnifiedSymEq (UnifiedSymEq)
import Grisette.Internal.Unified.EvalModeTag (EvalModeTag (C, S))
import Grisette.Internal.Unified.UnifiedBool (UnifiedBool (GetBool))
import Grisette.Internal.Unified.UnifiedBV (UnifiedBVImpl (GetIntN, GetWordN))
import Grisette.Internal.Unified.UnifiedInteger (GetInteger)

-- | Unified array type, the SMT theory of arrays under a unified evaluation
-- mode. Resolves to a concrete 'Grisette.Internal.SymPrim.Array.Array' in 'C'
-- mode, and a symbolic 'Grisette.Internal.SymPrim.SymArray.SymArray' in 'S'
-- mode.
--
-- When imported through "Grisette.Unified" the type is exposed /abstractly/:
-- only the canonicalizing smart constructors 'constArray'/'storeArray' (and the
-- reader 'selectArray') are available, never the raw data constructors. Unified
-- arrays are therefore always in canonical form, so equality (and concrete
-- 'C-mode '==') is extensional under the uniform-default invariant.
type family GetArray (mode :: EvalModeTag) k v = arr | arr -> mode k v where
  GetArray 'C k v = Array k v
  GetArray 'S k v = SymArray k v

-- | Mode-polymorphic array operations (the SMT theory of arrays:
-- @const@/@select@/@store@). The 'C-mode instance uses the concrete, canonical
-- array; the 'S-mode instance uses the symbolic array term.
class UnifiedArray (mode :: EvalModeTag) k v where
  -- | A constant array mapping every key to the given value.
  constArray :: v -> GetArray mode k v

  -- | Read the value stored at a key.
  selectArray :: GetArray mode k v -> k -> v

  -- | Write a value at a key. Writing a value equal to the array's default is
  -- canonicalized away, so the representation stays canonical.
  storeArray :: GetArray mode k v -> k -> v -> GetArray mode k v

instance (Hashable k, Eq v) => UnifiedArray 'C k v where
  constArray = CArr.const
  selectArray = CArr.select
  storeArray = CArr.store
  {-# INLINE constArray #-}
  {-# INLINE selectArray #-}
  {-# INLINE storeArray #-}

instance
  ( SupportedNonFuncPrim (ConType k),
    SupportedNonFuncPrim (ConType v),
    LinkedRep (ConType k) k,
    LinkedRep (ConType v) v
  ) =>
  UnifiedArray 'S k v
  where
  constArray = SArr.const
  selectArray = SArr.select
  storeArray = SArr.store
  {-# INLINE constArray #-}
  {-# INLINE selectArray #-}
  {-# INLINE storeArray #-}

-- | The constraint for a fully-featured unified array: the array operations
-- plus unified equality, if-then-else, and mergeability. With this in scope a
-- value containing a @GetArray mode k v@ can be compared with
-- 'Grisette.Unified..==', branched with unified if-then-else, and merged in
-- either mode.
type UnifiedArrayConstraint mode k v =
  ( UnifiedArray mode k v,
    Mergeable (GetArray mode k v),
    UnifiedSymEq mode (GetArray mode k v),
    UnifiedITEOp mode (GetArray mode k v),
    UnifiedSimpleMergeable mode (GetArray mode k v)
  )

-- | Implementation constraint for @WordN@-keyed unified arrays whose value is a
-- non-sized scalar (the unified @Bool@ and @Integer@). Indexed by the key width
-- @w@ so that 'EvalModeArray' can introduce one complete dictionary at the
-- operation boundary, mirroring the inner classes generated by
-- 'Grisette.Internal.Unified.UnifiedFun.genUnifiedFunInstance'.
class
  ( UnifiedArrayConstraint mode (GetWordN mode w) (GetBool mode),
    UnifiedArrayConstraint mode (GetWordN mode w) (GetInteger mode)
  ) =>
  UnifiedScalarArray (mode :: EvalModeTag) (w :: Nat)

instance (KnownNat w, 1 <= w) => UnifiedScalarArray 'C w

instance (KnownNat w, 1 <= w) => UnifiedScalarArray 'S w

-- | Implementation constraint for @WordN@-keyed unified arrays whose value is a
-- sized bit-vector (the unified @WordN n@ and @IntN n@). Indexed by the key
-- width @w@ and the value width @n@.
class
  ( UnifiedArrayConstraint mode (GetWordN mode w) (GetWordN mode n),
    UnifiedArrayConstraint mode (GetWordN mode w) (GetIntN mode n)
  ) =>
  UnifiedBVArray (mode :: EvalModeTag) (w :: Nat) (n :: Nat)

instance
  (KnownNat w, 1 <= w, KnownNat n, 1 <= n) => UnifiedBVArray 'C w n

instance
  (KnownNat w, 1 <= w, KnownNat n, 1 <= n) => UnifiedBVArray 'S w n

-- | Introduce finite-key array evidence only at the operation that needs it.
-- This is extensionally the old all-width contract without retaining two
-- quantified superclass dictionaries in every mode-polymorphic context.
class EvalModeArray (mode :: EvalModeTag) where
  -- | Supply arrays with a positive-width key and a scalar value.
  withBaseScalarArray ::
    forall w r.
    (KnownNat w, 1 <= w) =>
    (UnifiedScalarArray mode w => r) ->
    r

  -- | Supply arrays with positive-width keys and sized bit-vector values.
  withBaseBVArray ::
    forall w n r.
    (KnownNat w, 1 <= w, KnownNat n, 1 <= n) =>
    (UnifiedBVArray mode w n => r) ->
    r

instance EvalModeArray 'C where
  withBaseScalarArray result = result
  withBaseBVArray result = result

instance EvalModeArray 'S where
  withBaseScalarArray result = result
  withBaseBVArray result = result
